import { Avatar, Button, Tooltip } from "antd";
import Head from "next/head";
import Image from "next/image";
import DashboardLayout from "../../components/DashboardLayout";
import { Comment } from "@ant-design/compatible";
import Styles from "../../styles/pages/feedback.module.scss";
import { getFeedback } from "@/services/auth.service";
import { useQuery } from "react-query";
import moment from "moment";

export default function Home() {
  const { data, isLoading, isError } = useQuery("feedbacks", getFeedback);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout title="Dashboard">
        <div className={Styles.container}>
          {data?.feedback.map((feedback) => {
            return (
              <Comment
                style={{
                  marginBottom: "2rem",
                  padding: "0 1rem",
                  borderRadius: "20px",
                  boxShadow: "0 0 50px rgba(0,0,0,0.1)",
                }}
                author={<a>{feedback.name}</a>}
                avatar={
                  <Avatar
                    src="https://joeschmoe.io/api/v1/random"
                    alt="Han Solo"
                  />
                }
                content={<p>{feedback.description}</p>}
                datetime={
                  <Tooltip title={moment(feedback.date_time).toString()}>
                    {console.log(moment(feedback.date_time))}
                    <span>{moment(feedback.date_time).fromNow()}</span>
                  </Tooltip>
                }
              />
            );
          })}
        </div>
      </DashboardLayout>
    </div>
  );
}
