import { Button } from "antd";
import Head from "next/head";
import Image from "next/image";
import DashboardLayout from "../../components/DashboardLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout title="Dashboard">Hello</DashboardLayout>
    </div>
  );
}
