import Head from "next/head";
import { Inter } from "next/font/google";
import Styles from "../styles/pages/landing.module.scss";
import { Col, Image, Row } from "antd";
import Marquee from "react-fast-marquee";
import ImageSlider from "../components/ImgSlider.jsx";
import Lottie from "react-lottie";
import * as animationData from "../public/network.json";
import * as animationData1 from "../public/Innovation.json";
import * as animationData2 from "../public/hiring.json";
import Link from "next/link";
export default function Home() {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  const defaultOptions1 = {
    loop: true,
    autoplay: true,
    animationData: animationData1,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  const defaultOptions2 = {
    loop: true,
    autoplay: true,
    animationData: animationData2,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.container}>
        <div className={Styles.navbar}>
          <Image src="/innosphere_logo.png" alt="" preview={false}></Image>
          <Row>
            <div className={Styles.registerBtn}>
              {" "}
              <Link href="/startup-login">Startup Login</Link>{" "}
            </div>
            <div className={Styles.loginBtn}>
              <Link href="/student-login">Student Login</Link>
            </div>
          </Row>
        </div>
        <div className={Styles.hero}>
          <div className={Styles.heroText}>
            &quot;<span>Entrepreneurship</span> is not about having an idea,
            it&apos;s about having the <span>courage to take action</span> on
            that idea and turn it into a reality.&quot;
            <Row style={{ marginTop: "3rem" }}>
              <div className={Styles.registerBtn}>
                {" "}
                <Link href="/startup-signup">Register as Startup</Link>{" "}
              </div>
              <div className={Styles.loginBtn}>
                <Link href="/student-signup">Register as Student</Link>
              </div>
            </Row>
          </div>
          <div className={Styles.heroImage}>
            <Lottie
              options={defaultOptions1}
              height={400}
              width={400}
              style={{ margin: 0 }}
            />
          </div>
        </div>
        <div className={Styles.about}>
          <div className={Styles.aboutCarousel}>
            <ImageSlider />
          </div>
          <div className={Styles.startups}>
            <div className={Styles.aboutStats}>
              <div className={Styles.aboutStatsItem}>
                <div className={Styles.aboutStatsItemNumber}>40+</div>
                <div className={Styles.aboutStatsItemText}>Startups</div>
              </div>
              <div className={Styles.aboutStatsItem}>
                <div className={Styles.aboutStatsItemNumber}>100+</div>
                <div className={Styles.aboutStatsItemText}>Entrepreneurs</div>
              </div>
              <div className={Styles.aboutStatsItem}>
                <div className={Styles.aboutStatsItemNumber}>300+</div>
                Jobs
              </div>
            </div>
            <div className={Styles.aboutMarq}>
              <Marquee speed={"80"}>
                <Image src="/logos/1.svg" alt="" preview={false}></Image>
                <Image src="/logos/2.svg" alt="" preview={false}></Image>
                <Image src="/logos/3.png" alt="" preview={false}></Image>
                <Image src="/logos/4.png" alt="" preview={false}></Image>
                <Image src="/logos/5.png" alt="" preview={false}></Image>
                <Image src="/logos/6.png" alt="" preview={false}></Image>
              </Marquee>
            </div>
          </div>
        </div>
        <div className={Styles.aboutDeets}>
          <div className={Styles.about1}>
            <div>
              <h1
                style={{
                  fontSize: "2rem",
                  marginLeft: "2rem",
                }}
              >
                Network with the right people
              </h1>
              <h3
                style={{
                  fontSize: "1.4rem",
                  fontWeight: "400",
                  width: "80%",
                  marginLeft: "2rem",
                }}
              >
                Great things happen when great people come together. It’s magic!
              </h3>
            </div>
            <Lottie
              options={defaultOptions}
              height={400}
              width={400}
              style={{ margin: 0 }}
            />
          </div>
          <div className={Styles.about2}>
            <Lottie
              options={defaultOptions2}
              height={400}
              width={400}
              style={{ margin: 0 }}
            />
            <div
              style={{
                width: "40%",
              }}
            >
              <h1
                style={{
                  fontSize: "2rem",
                }}
              >
                Hire and Get Hired effectively
              </h1>
              <h3
                style={{
                  fontSize: "1.4rem",
                  fontWeight: "400",
                  width: "80%",
                }}
              >
                We help you find the right talent and help you get hired by the
                right people.
              </h3>
            </div>
            {/* give me more content ideas */}
          </div>
        </div>
        <div className={Styles.testimonials}>
          <div className={Styles.testimonialsTitle}>What our startups say</div>
          <div className={Styles.testimonialsCarousel}>
            <div className={Styles.testimonialsCarouselItem}>
              <Image src="/apos.png" alt="" preview={false}></Image>
              <div className={Styles.testimonialsCarouselItemTitle}>
                Fostering a culture of creativity
              </div>
              <div className={Styles.testimonialsCarouselItemText}>
                The innovation center has not only supported our startup but
                also paved the way for a better future. With their guidance and
                expertise, we were able to explore new ideas, test them out, and
                bring our vision to life.We thank them for the same and expect
                to return too.
              </div>
            </div>
            <div className={Styles.testimonialsCarouselItem}>
              <Image src="/apos.png" alt="" preview={false}></Image>
              <div className={Styles.testimonialsCarouselItemTitle}>
                Ocean of knowledge and expertise
              </div>
              <div className={Styles.testimonialsCarouselItemText}>
                The knowledge and expertise shared by IC have been crucial to
                the development of our startup. The mentorship provided by the
                innovation center team has helped us navigate through the
                challenges of entrepreneurship and has helped us stay focused on
                our goals.
              </div>
            </div>
            <div className={Styles.testimonialsCarouselItem}>
              <Image src="/apos.png" alt="" preview={false}></Image>
              <div className={Styles.testimonialsCarouselItemTitle}>
                Numerous opportunities and connects
              </div>
              <div className={Styles.testimonialsCarouselItemText}>
                I am grateful for the numerous opportunities you have provided
                us to connect with other startups and industry experts, helping
                us to expand our network and learn from others. Innovation
                Centre&apos;s commitment to promoting innovation and nurturing
                startups is truly commendable.
              </div>
            </div>
          </div>
        </div>
        <div className={Styles.footer}>INNOSPHERE</div>
      </div>
    </>
  );
}
