import { Button, Row, Skeleton } from "antd";
import Head from "next/head";
import Image from "next/image";
import DashboardLayout from "../../components/StudentDash";
import { Divider, List, Typography } from "antd";
import { Collapse, InfiniteScroll } from "antd";
import useAuth from "@/hooks/useAuth";

const { Panel } = Collapse;

import { Card } from "antd";
const { Meta } = Card;
export default function Home() {
  useAuth();
  const onChange = (key) => {
    console.log(key);
  };
  const data = [
    "Baylink just got funded $50,000",
    "Zenefit just got selected in GC cohort",
    "Fundinc just got selected in GC cohort",
    "Bugbase raised $500K from 100x.vc",
    "GoldenBird just raised $3M from an angel",
    "Formi is backed by 2AM VC now ",
    "Congratulations Baylink on a new private office ",
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout title="Dashboard">
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            width: "100%",
          }}
        >
          <Card
            hoverable
            style={{
              width: "200%",
              height: 320,
              margin: "20px",
            }}
            cover={
              <img
                alt="example"
                src="profile.png"
                style={{ height: "10rem", width: "10rem", margin: "auto" }}
              />
            }
          >
            <Meta
              title="Sakshat Gandhi"
              description="He is a god level coder "
            />
          </Card>
          <Collapse
            defaultActiveKey={["1"]}
            style={{ margin: "20px", width: "1000%" }}
            onChange={onChange}
          >
            <Panel header="Baylink" key="1">
              <p>
                The startup aims to assist direct-to-consumer (D2C) brands in
                establishing an offline retail presence through store
                collaborations and also providing them with an online storefront
                via our own e-commerce platform. The platform helps customers
                find the nearest store where the brand&apos;s products are
                available. Our solution aims to provide a comprehensive solution
                for D2C brands to reach both online and offline customers
                effectively
              </p>
            </Panel>
            <Panel header="Fundinc" key="2">
              <p>
                We want to increase accessiblity to investment opportunities in
                vetted early-stage startups working in the domains you believe
                in.
              </p>
            </Panel>
            <Panel header="Zenefit" key="3">
              <p>
                Zenefit is a B2B employee benefits platform designed for GenZ,
                the next generation of working millennials. It is a new,
                data-driven and highly personalised employee benefits platform
                that creates comprehensive, trusted recommendations for its
                members. Members have the power to choose the plans and benefits
                they value most, while also gaining access to exclusive
                discounts at select brand partners.
              </p>
            </Panel>
          </Collapse>
        </div>
        <div>
          <List
            size="large"
            header={<div>Announcements</div>}
            bordered
            dataSource={data}
            renderItem={(item) => (
              <List.Item
                style={{
                  color: "aliceblue",
                  fontSize: "1rem",
                  paddingLeft: "10px",
                }}
              >
                {item}
              </List.Item>
            )}
            style={{
              margin: "20px",
              backgroundColor: "rgba(26, 26, 26, 1)",
              color: "#c46d36",
              fontSize: "1.4rem",
              paddingLeft: "10px",
              height: "410px",
              overflow: "auto",
            }}
          />
        </div>
      </DashboardLayout>
    </div>
  );
}
